### ISSUE TITLE
Feature request: Karma and QUnit

### ISSUE THREAD

**Issue by Sciumo** [cdiggins/myna-parser#12]
It would be helpful to have an test harness and leverage qunit more effectively.
I propose using Karma and the QUnit karma plugin.

https://github.com/karma-runner/karma-qunit

**Comment by bd82** [comment]
I think there is perhaps a mixup of a couple different things here.

Karma is a test runner for JavaScript, but more precisely it runs tests in a **browser**.
So while a test harness is probably a good idea, going all the way to browser testing
is perhaps too far for an initial step.

@cdiggins If you are interested in some better testing tools have a look at some of the following.
- Mocha - https://mochajs.org/
- Jest - https://facebook.github.io/jest/
- Eva - https://github.com/avajs/ava

I only have experience with Mocha and afaik it is the only one compatible with running tests
in browsers via a karma plugin, this is a major advantage as it enables running tests
on Cloud Based testing services (sauceLabs) on multiple browsers.

However, browser testing is a pain to setup and get working initially so I would **not** start with that 😄 

Eva and Jest are newer testing frameworks which should have fancier features
(parallel testing, testing only code that could be affected for quick feedback, ...)
So if browser testing is less relevant perhaps start by checking out their features.

**anyhow a more modern testing framework is recommended** 😄 
instead of writing your own test runner as they will provide
better reporting, code coverage tools, automatic running in the background, CLI tools
and more...

**Comment by Sciumo** [comment]
Christopher already has QUnit tests (https://github.com/cdiggins/myna-parser/blob/master/tests/qunit.html), refactoring for karma is a step towards command line test automation. I have started and I'll provide a pull if I have further grammars I need testing.

**Comment by cdiggins** [comment]
I used to use Mocha to test on the command-line along with Instanbul to do code-coverage. At one point I thought it just complicated things, so I removed it. I could put it back.

**Comment by cdiggins** [comment]
I just re-added Mocha tests. This way we can run the same tests from both from the command-line or from QUnit.html. Hope this addresses this issue. Let me know if there is a good reason to prefer Karma to Mocha  for Myna.

**Comment by Sciumo** [comment]
Mocha is great. I'm getting a tsc build error I'll have to check.
myna.ts(859,64): error TS2304: Cannot find name 'console'.

**Comment by bd82** [comment]
> Let me know if there is a good reason to prefer Karma to Mocha for Myna.

These are not mutually exclusive, Karma can be used for running the mocha tests in
a **browser** it does not replace it.

**Comment by cdiggins** [comment]
@Sciumo if you install Myna using npm and run "npm test" does it work? It should not engage the TypeScript compiler.
